# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CustomPopUpPlusAnimations' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CustomPopUpPlusAnimations
  pod 'lottie-ios'

  target 'CustomPopUpPlusAnimationsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CustomPopUpPlusAnimationsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
